# Generated by Django 6.0.5 on 2026-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARTE', 'Carte bancaire'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money')], default='CARTE', max_length=20),
        ),
    ]
